resources:
- name: go-app
  type: git
  source: {uri: "https://github.com/topherbullock/ci-example-go.git"}

- name: spring-boot-app
  type: git
  source: {uri: "https://github.com/topherbullock/ci-example-spring-boot.git"}

- name: go-app-test-deploy
  type: cf
  source: &cf_config
    api: https://api.run.pivotal.io
    username: ((cf-username))
    password: ((cf-password))
    organization: topherbullock
    space: development
    skip_cert_check: false

- name: spring-app-test-deploy
  type: cf
  source: *cf_config

jobs:
- name: go-unit
  plan:
  - get: go-app
    trigger: true
  - task: test
    file: go-app/ci/test.yml

- name: spring-unit
  plan:
  - get: spring-boot-app
    trigger: true
  - task: test
    file: spring-boot-app/ci/test.yml

- name: integration-test
  plan:
    - get: spring-boot-app
      passed: [spring-unit]
      trigger: true
    - get: go-app
      passed: [go-unit]
      trigger: true
    # - task: run-test
    #   file: go-app/ci/failing_integration_test.yml

- name: dev-deploy
  plan:
    - aggregate:
      - do:
        - get: go-app
          passed: [integration-test]
          trigger: true
        - task: build-go-app
          file: go-app/ci/build.yml
      - do:
        - get: spring-boot-app
          passed: [integration-test]
          trigger: true
        - task: package-spring-app
          file: spring-boot-app/ci/build.yml
    - aggregate:
      - put: go-app-test-deploy
        params:
          manifest: ci-example-go/manifest.yml
          path: ci-example-go
      - put: spring-app-test-deploy
        params:
          manifest: spring-boot-app-packaged/manifest.yml
          path: spring-boot-app-packaged

# - name: acceptance-tests
#   plan:
#     - aggregate:
#       - get: go-app-test-deploy
#         passed: [dev-deploy]
#       - get: spring-app-test-deploy
#         passed: [dev-deploy]
#       - get: go-app
#         passed: [dev-deploy]
#     - task: run-test
#       file: go-app/ci/failing_integration_test.yml
